version: "3"

services:
  infraui:
    container_name: ui
    image: infraui
    restart: always
    environment:
      - REACT_APP_API_END_POINT=http://infraapi:8080
    ports:
      - 3000:80
    networks:
      - app_network
  infraapi:
    container_name: api
    image: infraapi
    environment:
      - CASSANDRA_CONTACT_POINTS=/usr/src/config/cassandra.yml
    volumes:
      - ./config/cassandra.yml:/usr/src/config/cassandra.yml
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network
  cassandra-db:
    image: cassandra:3.11.10
    container_name: cassandra-db
    hostname: cassandra-db
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - app_network
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-db:/var/lib/cassandra
    environment: &environment
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
networks:
  app_network: