name: Build and Push UI Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'apps/ui/**'

jobs:
  build-and-push-ui:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build UI Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/ui:latest apps/ui
        docker push ghcr.io/${{ github.repository }}/ui:latest
