name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build API Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/api:latest apps/api/Dockerfile

    - name: Build UI Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/ui:latest apps/ui/Dockerfile

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}/api:latest
        docker push ghcr.io/${{ github.repository }}/ui:latest