name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'apps/ui/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push API Docker image
      if: ${{ github.event_name == 'push' && contains(github.event.compare, 'apps/api/') }}
      run: |
        docker build -t ghcr.io/${{ github.repository }}/api:latest apps/api
        docker push ghcr.io/${{ github.repository }}/api:latest

    - name: Build and Push UI Docker image
      if: ${{ github.event_name == 'push' && contains(github.event.compare, 'apps/ui/') }}
      run: |
        docker build -t ghcr.io/${{ github.repository }}/ui:latest apps/ui
        docker push ghcr.io/${{ github.repository }}/ui:latest
