name: Build and Push API Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build API Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/api:latest apps/api
        docker push ghcr.io/${{ github.repository }}/api:latest
